print(2 + 3)
print(3 - 1)
print(2 * 3)
print(3 / 2)
print(2 ** 3)
print(2 % 3)
print(2 // 3)
print("maria")
print("python")
print("españa")
print("I am enjoying 30 days de python")
print((type)(10))
print((type)(9.8))
print((type)(3.14))
print((type)(4-4j))
print((type)(['maria', 'python', 'españa']))
print((type)("maria"))
print((type)("python"))
print((type)("españa"))
print((type)("7"))
print((type)("3.5"))
print((type)("4a"))
print((type)("hola mundo"))
print (True) # Do I like dance? If I like it, then value is true
print(False) # Do I like dance? If I like it, then value is false